import {
  Award,
  BatteryWarning,
  Cable,
  CameraOff,
  Disc3,
  Droplets,
  Gamepad2,
  Headphones,
  Headset,
  Home,
  KeyboardOff,
  Laptop,
  MonitorX,
  Package,
  PackageCheck,
  PlugZap,
  Power,
  RefreshCcwDot,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  Tablet,
  ThermometerSun,
  Truck,
  Undo2,
  Users,
  VolumeOff,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

/** نگاشت نام آیکون (که در دیتای CMS ذخیره می‌شود) به کامپوننت */
export const iconMap: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  laptop: Laptop,
  'gamepad-2': Gamepad2,
  'disc-3': Disc3,
  headphones: Headphones,
  headset: Headset,
  'shield-check': ShieldCheck,
  truck: Truck,
  home: Home,
  store: Store,
  wrench: Wrench,
  package: Package,
  tablet: Tablet,
  'monitor-x': MonitorX,
  'battery-warning': BatteryWarning,
  'plug-zap': PlugZap,
  droplets: Droplets,
  'power-off': Power,
  'thermometer-sun': ThermometerSun,
  cable: Cable,
  'keyboard-off': KeyboardOff,
  'refresh-ccw-dot': RefreshCcwDot,
  'camera-off': CameraOff,
  'volume-off': VolumeOff,
  users: Users,
  award: Award,
  'package-check': PackageCheck,
  sparkles: Sparkles,
  'undo-2': Undo2,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Package
}
